/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as SecurityServiceRouteImport } from './routes/security-service'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as CfoRouteImport } from './routes/cfo'
import { Route as AgroRouteImport } from './routes/agro'
import { Route as IndexRouteImport } from './routes/index'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityServiceRoute = SecurityServiceRouteImport.update({
  id: '/security-service',
  path: '/security-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const CfoRoute = CfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgroRoute = AgroRouteImport.update({
  id: '/agro',
  path: '/agro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
  id:
    | '__root__'
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgroRoute: typeof AgroRoute
  CfoRoute: typeof CfoRoute
  LogisticsRoute: typeof LogisticsRoute
  MemoryRoute: typeof MemoryRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityServiceRoute: typeof SecurityServiceRoute
  WhitepaperRoute: typeof WhitepaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-service': {
      id: '/security-service'
      path: '/security-service'
      fullPath: '/security-service'
      preLoaderRoute: typeof SecurityServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cfo': {
      id: '/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof CfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agro': {
      id: '/agro'
      path: '/agro'
      fullPath: '/agro'
      preLoaderRoute: typeof AgroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgroRoute: AgroRoute,
  CfoRoute: CfoRoute,
  LogisticsRoute: LogisticsRoute,
  MemoryRoute: MemoryRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityServiceRoute: SecurityServiceRoute,
  WhitepaperRoute: WhitepaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
