/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgroRouteImport } from './routes/agro'
import { Route as CfoRouteImport } from './routes/cfo'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityServiceRouteImport } from './routes/security-service'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsFrankensteinSyndromeRouteImport } from './routes/insights/frankenstein-syndrome'
import { Route as InsightsTamingLocalAiRouteImport } from './routes/insights/taming-local-ai'
import { Route as SolutionsExecutiveCopilotRouteImport } from './routes/solutions/executive-copilot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgroRoute = AgroRouteImport.update({
  id: '/agro',
  path: '/agro',
  getParentRoute: () => rootRouteImport,
} as any)
const CfoRoute = CfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityServiceRoute = SecurityServiceRouteImport.update({
  id: '/security-service',
  path: '/security-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsFrankensteinSyndromeRoute =
  InsightsFrankensteinSyndromeRouteImport.update({
    id: '/insights/frankenstein-syndrome',
    path: '/insights/frankenstein-syndrome',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsTamingLocalAiRoute = InsightsTamingLocalAiRouteImport.update({
  id: '/insights/taming-local-ai',
  path: '/insights/taming-local-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsExecutiveCopilotRoute =
  SolutionsExecutiveCopilotRouteImport.update({
    id: '/solutions/executive-copilot',
    path: '/solutions/executive-copilot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
  '/insights/frankenstein-syndrome': typeof InsightsFrankensteinSyndromeRoute
  '/insights/taming-local-ai': typeof InsightsTamingLocalAiRoute
  '/solutions/executive-copilot': typeof SolutionsExecutiveCopilotRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
  '/insights/frankenstein-syndrome': typeof InsightsFrankensteinSyndromeRoute
  '/insights/taming-local-ai': typeof InsightsTamingLocalAiRoute
  '/solutions/executive-copilot': typeof SolutionsExecutiveCopilotRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agro': typeof AgroRoute
  '/cfo': typeof CfoRoute
  '/logistics': typeof LogisticsRoute
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/security-service': typeof SecurityServiceRoute
  '/whitepaper': typeof WhitepaperRoute
  '/insights/frankenstein-syndrome': typeof InsightsFrankensteinSyndromeRoute
  '/insights/taming-local-ai': typeof InsightsTamingLocalAiRoute
  '/solutions/executive-copilot': typeof SolutionsExecutiveCopilotRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
    | '/insights/frankenstein-syndrome'
    | '/insights/taming-local-ai'
    | '/solutions/executive-copilot'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
    | '/insights/frankenstein-syndrome'
    | '/insights/taming-local-ai'
    | '/solutions/executive-copilot'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/agro'
    | '/cfo'
    | '/logistics'
    | '/memory'
    | '/privacy'
    | '/security-service'
    | '/whitepaper'
    | '/insights/frankenstein-syndrome'
    | '/insights/taming-local-ai'
    | '/solutions/executive-copilot'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgroRoute: typeof AgroRoute
  CfoRoute: typeof CfoRoute
  LogisticsRoute: typeof LogisticsRoute
  MemoryRoute: typeof MemoryRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityServiceRoute: typeof SecurityServiceRoute
  WhitepaperRoute: typeof WhitepaperRoute
  InsightsFrankensteinSyndromeRoute: typeof InsightsFrankensteinSyndromeRoute
  InsightsTamingLocalAiRoute: typeof InsightsTamingLocalAiRoute
  SolutionsExecutiveCopilotRoute: typeof SolutionsExecutiveCopilotRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agro': {
      id: '/agro'
      path: '/agro'
      fullPath: '/agro'
      preLoaderRoute: typeof AgroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cfo': {
      id: '/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof CfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-service': {
      id: '/security-service'
      path: '/security-service'
      fullPath: '/security-service'
      preLoaderRoute: typeof SecurityServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/frankenstein-syndrome': {
      id: '/insights/frankenstein-syndrome'
      path: '/insights/frankenstein-syndrome'
      fullPath: '/insights/frankenstein-syndrome'
      preLoaderRoute: typeof InsightsFrankensteinSyndromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/taming-local-ai': {
      id: '/insights/taming-local-ai'
      path: '/insights/taming-local-ai'
      fullPath: '/insights/taming-local-ai'
      preLoaderRoute: typeof InsightsTamingLocalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/executive-copilot': {
      id: '/solutions/executive-copilot'
      path: '/solutions/executive-copilot'
      fullPath: '/solutions/executive-copilot'
      preLoaderRoute: typeof SolutionsExecutiveCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgroRoute: AgroRoute,
  CfoRoute: CfoRoute,
  LogisticsRoute: LogisticsRoute,
  MemoryRoute: MemoryRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityServiceRoute: SecurityServiceRoute,
  WhitepaperRoute: WhitepaperRoute,
  InsightsFrankensteinSyndromeRoute: InsightsFrankensteinSyndromeRoute,
  InsightsTamingLocalAiRoute: InsightsTamingLocalAiRoute,
  SolutionsExecutiveCopilotRoute: SolutionsExecutiveCopilotRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
